/*Author:       Dan Truong  ;  Partner: John Bui
  CLID:         dmt9492 C00047648  ;   C00076582
  Class:        CMPS 358
  Assignment:   assignment­ 8
  Due Date:     03/25/2019 11:55 => extension to 03/27/2019 11:59
  Description:  This project is a reduced copy of the classic Salvo game. Each player gets a 5x5 grid with a 
                randomly placed ship. Each player takes turns firing until a ship is destroyed. This project
                demonstrates a use of sockets and server/client methods to exchange data to two different computers.

  Certification of Authenticity:
    We certify that the code in the classes of this project, other than code provided the instructions for
    this assignment or generated by Visual Studio is entirely our own work. */

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Net.Sockets;
using System.Net;
using System.IO;

namespace pa8_secondtry
{
    public partial class Salvo : Form
    {
        private TcpClient client;
        private StreamReader read;
        private StreamWriter write;
        private String positionTake;
        private String positionShoot;
        private Random x = new Random();
        private Boolean turnnotDecide = true;
        private int turn = 0;
        private int turn2 = 0;
        private int hitCount = 0;
        private int hitCount2 = 0;
                        
        private void decideFirst()      //This method decides which player goes first and sends data to let the other
                                         //player know.
        {
            turn = x.Next(0, 2);
            if(turn == 1)
            {
                turn2 = 0;
            }
            else
            {
                turn2 = 1;
            }
            dataSender(turn.ToString());
            turnnotDecide = false;
        }

        public Salvo()
        {
            InitializeComponent();
        }

        private void startServer_Click(object sender, EventArgs e)      //When this button is clicked, a server is started,
                                                                       //where a listener is used to find a client.
        {
            TcpListener listen = new TcpListener(IPAddress.Any, 12345);
            listen.Start();
            client = listen.AcceptTcpClient();
            read = new StreamReader(client.GetStream());
            write = new StreamWriter(client.GetStream());
            write.AutoFlush = true;
                                                                   //A backgroundworker is created to start receiving data.
            backgroundWorker1.RunWorkerAsync();
                                                                    //Methods to show and hide certain controls.
            textBox1.Show();
            startServer.Hide();
            connectClient.Hide();
            label3.Hide();
            label4.Hide();
            IPBox.Hide();
            portBox.Hide();
            initializeShip();
            decideFirst();
            shootTip.Show();
        }

        private void connectClient_Click(object sender, EventArgs e)    //When this button is clicked, the client sends an address and port to
                                                                        //find a server.
        {
            client = new TcpClient();
            System.Threading.Thread.Sleep(600);
                                                                         //User given the option to input an IP address.
            IPEndPoint IP = new IPEndPoint(IPAddress.Parse(IPBox.Text), Int32.Parse(portBox.Text));

            try
            {
                client.Connect(IP);
                if (client.Connected)
                {
                    read = new StreamReader(client.GetStream());
                    write = new StreamWriter(client.GetStream());
                    write.AutoFlush = true;
                                                                     //After attempting to connect, a backgroundworker is started.
                    backgroundWorker1.RunWorkerAsync();
                    
                }
            }
            catch (Exception ex)
            {
                MessageBox.Show(ex.Message);
            }
                                                               //The following lines are written to hide and show controls accordingly.
            connectClient.Hide();
            startServer.Hide();
            label3.Hide();
            label4.Hide();
            IPBox.Hide();
            portBox.Hide();
            textBox1.Show();
            initializeShip();
            System.Threading.Thread.Sleep(1000);
            decideFirst();
            shootTip.Show();
        }

        private void initializeShip()                  //This method initializes a ship for each player.
                                                       //It randomly selects a horizontal or vertical orientation, then 
                                                       //marks your ship on your board.
        {
            int orientation = x.Next(0, 2);
            if (orientation == 0)               //vertical ship selection
            {
                int pos = x.Next(51, 66);
                foreach (Control y in Controls)
                {
                    if (y.TabIndex == pos)
                    {
                        y.BackColor = Color.Black;
                    }
                    if (y.TabIndex == (pos + 5))
                    {
                        y.BackColor = Color.Black;
                    }
                    if (y.TabIndex == (pos + 10))
                    {
                        y.BackColor = Color.Black;
                    }
                }
            }
            else                               //Horizontal ship selection.
            {
                Boolean posnotFound = true;
                while (posnotFound)
                {
                    int pos2 = x.Next(51, 74);
                    if (pos2 % 5 != 0 && (pos2 + 1) % 5 != 0)
                    {
                        foreach (Control y in Controls)
                        {
                            if (y.TabIndex == pos2)
                            {
                                y.BackColor = Color.Black;
                            }
                            if (y.TabIndex == (pos2 + 1))
                            {
                                y.BackColor = Color.Black;
                            }
                            if (y.TabIndex == (pos2 + 2))
                            {
                                y.BackColor = Color.Black;
                            }
                        }
                        posnotFound = false;
                    }
                }
            }
        }

        private void backgroundWorker1_DoWork(object sender, DoWorkEventArgs e)
        {                                                        //Backgroundworker receives data and sends accordingly.
            while (client.Connected)
            {
                try
                {
                    while (turnnotDecide)           //This receives the answer to decideFirst method, marking who is allowed to go first.
                    {
                        turn2 = Int32.Parse(read.ReadLine());
                        if(turn2 == 1)
                        {
                            turn = 0;
                        }
                        else
                        {
                            turn = 1;
                        }
                        turnnotDecide = false;            //Boolean to ensure that the decision will not be made again.
                        
                    }
                    positionTake = read.ReadLine();         //This block takes a string from sender and marks the enemy board accordingly.
                                                            //This is to tell the player whether their shot was a hit or miss.
                    int choicePos = Int32.Parse(positionTake);  //Changes the string position to integer.
                    if(choicePos < 26)                     
                    {
                        foreach (Control x in Controls)         //Marking of board if player hit the other player.
                        {
                            if (x.TabIndex == choicePos)
                            {
                                x.Invoke(new MethodInvoker(delegate ()
                                {
                                    x.BackColor = Color.Red;
                                    x.Text = "X";
                                    x.Font = new Font(x.Font, x.Font.Style | FontStyle.Bold);
                                    x.Font = new Font(x.Font.Name, 15, x.Font.Style, x.Font.Unit);
                                    x.Enabled = false;
                                }));
                                textBox1.Invoke(new MethodInvoker(delegate ()
                                {
                                    textBox1.Text = "Hit!";
                                }));
                                hitCount2++;
                                if (hitCount2 == 3)
                                {
                                    foreach (Control y in Controls)
                                    {
                                        y.Invoke(new MethodInvoker(delegate ()
                                        {
                                            y.Enabled = false;
                                        }));
                                    }
                                    textBox1.Invoke(new MethodInvoker(delegate ()
                                    {
                                        textBox1.Text = "Game Over!";
                                    }));
                                }
                            }
                        }
                    }
                    else if(choicePos > 200)            //Marking a miss if the player miss the other player.
                    {
                        choicePos -= 250;
                        foreach (Control x in Controls)
                        {
                            if (x.TabIndex == choicePos)
                            {
                                x.Invoke(new MethodInvoker(delegate ()
                                {
                                    x.BackColor = Color.Gray;
                                    x.Text = ":(";
                                    x.Font = new Font(x.Font, x.Font.Style | FontStyle.Bold);
                                    x.Font = new Font(x.Font.Name, 15, x.Font.Style, x.Font.Unit);
                                    x.Enabled = false;
                                }));
                                textBox1.Invoke(new MethodInvoker(delegate ()
                                {
                                    textBox1.Text = "Miss!";
                                }));
                            }
                        }
                    }
                    else
                    {
                        if (turn > turn2)               //Check to make sure that it was the other player's turn.
                        {
                            foreach (Control x in Controls)
                            {
                                if (x.TabIndex == choicePos)    //Check to see if the other player hit you.
                                {
                                    if (x.BackColor == Color.Blue)
                                    {
                                        x.Invoke(new MethodInvoker(delegate ()
                                        {
                                            x.BackColor = Color.Gray;
                                            x.Text = ":(";
                                            x.Font = new Font(x.Font, x.Font.Style | FontStyle.Bold);
                                            x.Font = new Font(x.Font.Name, 15, x.Font.Style, x.Font.Unit);
                                        }));
                                        textBox1.Invoke(new MethodInvoker(delegate ()
                                        {
                                            textBox1.Text = ("They missed!");
                                        }));
                                        dataSender((x.TabIndex+200).ToString());
                                        turn--;
                                        turn2++;
                                    }
                                    else if(x.BackColor == Color.Black)             //If you've been hit this marks your board.
                                    {
                                        x.Invoke(new MethodInvoker(delegate ()
                                        {
                                            x.BackColor = Color.Red;
                                            x.Text = "X";
                                            x.Font = new Font(x.Font,x.Font.Style | FontStyle.Bold);
                                            x.Font = new Font(x.Font.Name, 15, x.Font.Style, x.Font.Unit);
                                        }));
                                        
                                        textBox1.Invoke(new MethodInvoker(delegate ()
                                        {
                                            textBox1.Text = ("You've been hit!");
                                        }));
                                        dataSender((x.TabIndex - 50).ToString());
                                        hitCount++;                             //Increment, to determine if you've lost.
                                        if (hitCount == 3)
                                        {
                                            foreach (Control y in Controls)
                                            {
                                                y.Invoke(new MethodInvoker(delegate ()
                                                {
                                                    y.Enabled = false;
                                                }));
                                            }
                                            textBox1.Invoke(new MethodInvoker(delegate ()
                                            {
                                                textBox1.Text = "Game Over!";       //To end the game.
                                            }));
                                        }
                                        turn--;
                                        turn2++;
                                    }
                                }
                                positionTake = "";
                            }
                        }
                    }
                }
                    
                catch (Exception ex)
                {
                    MessageBox.Show(ex.Message);
                }
            }
        }

        private async void dataSender(String x)         //Method to send data.
        {
            await write.WriteLineAsync(x);
        }

        private void button5_Click(object sender, EventArgs e)      //When this control is used, it will send data of which position to mark.
        {
            Button y = sender as Button;

            positionShoot = (y.TabIndex + 50).ToString();
            dataSender(positionShoot);

            if (turn < turn2)       //Ensures that it is your turn to shoot.
            {
                turn++;
                turn2--;
            }
        }
    }
    }

